### ISSUE TITLE
error: incorrect authentication

### ISSUE THREAD

**Issue by veekas** [rousan/linkedin-auto-connect#2]
Receiving this error message when I enter the correct password to my LinkedIn account. Not sure how to troubleshoot. Any ideas?

```
> lac -u me@myemailaddress.com
Enter LinkedIn password:

  Connecting to the LinkedIn server..
  Connected.

  error:   incorrect authentication
```

**Comment by rousan** [comment]
Hi @veekas,
This error is raised because of you entered a wrong LinkedIn email address or wrong password.

You can troubleshoot by followings:
1. Try to login with the entered email or password in a browser.
2. Use LinkedIn email and password used when you log in to LinkedIn in a browser.

**Comment by veekas** [comment]
Thanks, @rousan. I copied the email/pw directly from LastPass, and I confirmed that they work when logging in with a different browser manually, so I'm sure that my authentication info correct.

**Comment by rousan** [comment]
Hello @veekas,
If `Two-Step Verification` is enabled on your account, then it will not work, so make sure you didn't enable `Two-Step Verification`.

**Comment by veekas** [comment]
Oh, that must be it. Thanks! Closing the issue.
