### ISSUE TITLE
Keyword problem unknown option -k

### ISSUE THREAD

**Issue by Satibo** [rousan/linkedin-auto-connect#7]
I tried lac -u <username> -k <hr-manager>
It gave me this as a result:   error: unknown option `-k'

Any explanation?

**Comment by rousan** [comment]
@Satibo 
Why are you using the option `-k`?, This tool doesn't know about the `-k` option.

**Comment by Satibo** [comment]
The read me file said that we could implement a key word when auto connecting?

**Comment by rousan** [comment]
@Satibo 
I don't think so, can you refer that section?

**Comment by Satibo** [comment]
$ lac -u <enter_your_linkedin_email> -k <keyword like Full Stack Developer>
Enter LinkedIn password: *****

**In the keyword argument, if you type "ALL" then this tool will send invitations request to the people you may know or else you can send the connect with the particular niche people like full stack developer, UI/UX, investors etc.**

Also right now when using the program a lot of my requests fail. Is there any reason why?

**Comment by Satibo** [comment]
$ lac -u <enter_your_linkedin_email> -k <keyword like Full Stack Developer>

**Comment by agarwalyeshu** [comment]
@Satibo  Use this one. 
https://github.com/agarwalyeshu/linkedin-auto-connect

**Comment by Satibo** [comment]
Ok i tried that but it didn't ask me for my username:

![image](https://user-images.githubusercontent.com/43171412/45554178-09629300-b836-11e8-802f-e84bc137431d.png)

**Comment by Satibo** [comment]
Ok i tried that but it didn't ask me for my username:

[Afbeelding github.pdf](https://github.com/rousan/linkedin-auto-connect/files/2383578/Afbeelding.github.pdf)

**Comment by Satibo** [comment]
Ok i tried that but it didn't ask me for my username:

[Picture Github.pdf](https://github.com/rousan/linkedin-auto-connect/files/2383586/Picture.Github.pdf)

**Comment by rousan** [comment]
@Satibo 
Please read the README, you need to pass email and the password, not the username, like below:
```
lac -u <your_email> -p
Enter Linkedin password: <type your password>
```

**Comment by Satibo** [comment]
I did what you told me and it works but the connections he is trying to make fail. 
![image](https://user-images.githubusercontent.com/43171412/45557285-87766800-b83d-11e8-96c1-facdca92b9ff.png)

Thank you for the support so far, really helpful!

**Comment by Satibo** [comment]
I did what you told me and it works but the connections he is trying to make fail, all of them.

Thank you for the support so far, really helpful!

**Comment by Satibo** [comment]
I did what you told me and it works but the connections he is trying to make fail, all of them.

Thank you for the support so far, really helpful!
[Failed connection picture.pdf](https://github.com/rousan/linkedin-auto-connect/files/2383795/Failed.connection.picture.pdf)

**Comment by rousan** [comment]
@Satibo 
Probably, You have reached the maximum limit of invitation requests. So, try again after some time. It should work.

**Comment by Satibo** [comment]
Hey Rousan, 

After using it for almost 2 weeks very well, i'm now getting this message every time I initiate the program. 
What can I do? I'm very pleased with the program and it works like a charm so I would like to continue using it. 

<img width="1269" alt="schermafbeelding 2018-09-26 om 09 30 37" src="https://user-images.githubusercontent.com/43171412/46064455-bc54ba00-c16f-11e8-86a3-07450c53087f.png">

**Comment by rousan** [comment]
@Satibo,
Thank you very much for reporting this blocker issue. I just made a new release `v1.0.2` with bugfix.

Check it out.
```bash
npm update -g linkedin-auto-connect
```
